### ISSUE TITLE
No signature assignment in SmppTransmitter constructor

### ISSUE THREAD

**Issue by Siao-pin** [kronas/SmppClientBundle#1]
During creation a new SmppTransmitter instance there is no assignment "signature" input variable to object's private "signature" property.

**Comment by dhanzhelo** [comment]
Please provide me more information about the case you are referring to.

**Comment by Siao-pin** [comment]
Sorry, maybe it was problem with default version pulled from packagist. `1.0.0-dev` version installation failed with error:

>  Problem 1
>     - The requested package kronas/smpp-client-bundle could not be found in any version, there may be a typo in the package name.

I tryied `^1.0`, but it was old version with `signature` bug mention above. Meanwhile `dev-master` version is working as expected.
